package br.com.murilo.liberthia.magic.factory;

import net.minecraft.world.item.ItemStack;

import java.util.HashMap;
import java.util.Map;

/**
 * r155-r157: Mapeamento estável de spell ID → índice numérico usado pelo
 * {@code liberthia:spell_index} ItemPropertyFunction.
 *
 * <p>Auto-gerado por {@code gen_spell_textures.py}. Não editar manualmente.
 */
public final class FactorySpellIndex {

    private static final Map<String, Integer> IDX = new HashMap<>(128);
    static {
        // Generated by gen_spell_textures.py — do not edit manually
        IDX.put("factory_aetheric_pulse", 1);
        IDX.put("factory_amethyst_lance", 2);
        IDX.put("factory_amethyst_shards", 3);
        IDX.put("factory_arcane_ward", 4);
        IDX.put("factory_aurora_beam", 5);
        IDX.put("factory_berserker_rage", 6);
        IDX.put("factory_blessing", 7);
        IDX.put("factory_blink_step", 8);
        IDX.put("factory_blood_moon_aura", 9);
        IDX.put("factory_burning_aura", 10);
        IDX.put("factory_chrono_dash", 11);
        IDX.put("factory_critical_strike", 12);
        IDX.put("factory_crystal_bloom", 13);
        IDX.put("factory_crystal_storm", 14);
        IDX.put("factory_dash_00", 15);
        IDX.put("factory_dash_01", 16);
        IDX.put("factory_dash_02", 17);
        IDX.put("factory_dash_03", 18);
        IDX.put("factory_dash_04", 19);
        IDX.put("factory_death_beam", 20);
        IDX.put("factory_devil_walk", 21);
        IDX.put("factory_dim_blind_curse", 22);
        IDX.put("factory_dimensional_rupture", 23);
        IDX.put("factory_dispell", 24);
        IDX.put("factory_divine_mantle", 25);
        IDX.put("factory_dragon_breath", 26);
        IDX.put("factory_dragon_roar", 27);
        IDX.put("factory_earthquake", 28);
        IDX.put("factory_fireball", 29);
        IDX.put("factory_frost_armor", 30);
        IDX.put("factory_frost_nova", 31);
        IDX.put("factory_ghost_step", 32);
        IDX.put("factory_glacial_tomb", 33);
        IDX.put("factory_gravity_well", 34);
        IDX.put("factory_great_spell", 35);
        IDX.put("factory_group_glow", 36);
        IDX.put("factory_group_haste", 37);
        IDX.put("factory_group_heal", 38);
        IDX.put("factory_group_invis", 39);
        IDX.put("factory_group_jump", 40);
        IDX.put("factory_group_resist", 41);
        IDX.put("factory_group_speed", 42);
        IDX.put("factory_group_strength", 43);
        IDX.put("factory_haunted_inv", 44);
        IDX.put("factory_hemorrhage_wave", 45);
        IDX.put("factory_homing_missile", 46);
        IDX.put("factory_ice_storm", 47);
        IDX.put("factory_immortal_00", 48);
        IDX.put("factory_immortal_01", 49);
        IDX.put("factory_immortal_02", 50);
        IDX.put("factory_immortal_03", 51);
        IDX.put("factory_immortal_04", 52);
        IDX.put("factory_iron_skin", 53);
        IDX.put("factory_lava_lance", 54);
        IDX.put("factory_levitate_self", 55);
        IDX.put("factory_life_drain", 56);
        IDX.put("factory_magnet_pull", 57);
        IDX.put("factory_mana_burst", 58);
        IDX.put("factory_mana_drain", 59);
        IDX.put("factory_mass_root", 60);
        IDX.put("factory_mass_silence", 61);
        IDX.put("factory_mass_slow", 62);
        IDX.put("factory_meteor", 63);
        IDX.put("factory_meteor_00", 64);
        IDX.put("factory_meteor_01", 65);
        IDX.put("factory_meteor_02", 66);
        IDX.put("factory_meteor_03", 67);
        IDX.put("factory_meteor_04", 68);
        IDX.put("factory_meteor_05", 69);
        IDX.put("factory_meteor_06", 70);
        IDX.put("factory_meteor_07", 71);
        IDX.put("factory_meteor_08", 72);
        IDX.put("factory_meteor_09", 73);
        IDX.put("factory_meteor_storm", 74);
        IDX.put("factory_mind_lance", 75);
        IDX.put("factory_mirror_walk", 76);
        IDX.put("factory_movement_00", 77);
        IDX.put("factory_movement_01", 78);
        IDX.put("factory_movement_02", 79);
        IDX.put("factory_movement_03", 80);
        IDX.put("factory_movement_04", 81);
        IDX.put("factory_movement_05", 82);
        IDX.put("factory_movement_06", 83);
        IDX.put("factory_movement_07", 84);
        IDX.put("factory_mud_prison", 85);
        IDX.put("factory_necrotic_storm", 86);
        IDX.put("factory_nightmare", 87);
        IDX.put("factory_phase_dash", 88);
        IDX.put("factory_phoenix_dive", 89);
        IDX.put("factory_pox_swarm", 90);
        IDX.put("factory_purify_aura", 91);
        IDX.put("factory_regeneration_field", 92);
        IDX.put("factory_sand_blast", 93);
        IDX.put("factory_shadow_cloak", 94);
        IDX.put("factory_shadow_clone", 95);
        IDX.put("factory_solar_flare", 96);
        IDX.put("factory_soul_link", 97);
        IDX.put("factory_soul_shatter", 98);
        IDX.put("factory_steam_explosion", 99);
        IDX.put("factory_stone_shield", 100);
        IDX.put("factory_tempest_strike", 101);
        IDX.put("factory_thunder_step", 102);
        IDX.put("factory_time_dilate", 103);
        IDX.put("factory_triple_shot", 104);
        IDX.put("factory_vampires_kiss", 105);
        IDX.put("factory_vampiric_touch", 106);
        IDX.put("factory_vazio_roxo", 107);
        IDX.put("factory_vertigo_curse", 108);
        IDX.put("factory_void_aegis", 109);
        IDX.put("factory_void_dash", 110);
        IDX.put("factory_void_heart", 111);
        IDX.put("factory_void_lance", 112);
        IDX.put("factory_void_pull", 113);
        IDX.put("factory_void_singularity", 114);
        IDX.put("factory_volcanic_storm", 115);
        IDX.put("factory_whispers_curse", 116);
        IDX.put("factory_wisp_swarm", 117);

    }

    private FactorySpellIndex() {}

    /** Retorna índice float pro ItemPropertyFunction. 0 = sem textura customizada. */
    public static float indexFor(ItemStack stack) {
        String id = DynamicSpellItem.spellId(stack);
        if (id == null) return 0f;
        Integer i = IDX.get(id);
        return i == null ? 0f : (float) i;
    }

    public static int countMapped() { return IDX.size(); }
}
