"""Empacota assets de um bloco (model JSON + textura PNG + blockstate)
num resource pack ZIP unico pronto pra usar.

Tambem suporta gerar o pacote a partir do bbmodel (lendo a textura embutida).

Usage:
    python bb_to_resourcepack.py --bbmodel armor_angel.bbmodel --output armor_angel_pack.zip
    OU
    python bb_to_resourcepack.py --from-mod-name armor_angel --output armor_angel_pack.zip
"""
import argparse
import base64
import json
import os
import sys
import zipfile
from datetime import datetime


def create_pack_mcmeta(description, pack_format=15):
    """pack_format 15 = Minecraft 1.20.x.
    Outros: 8=1.18, 9=1.19, 12=1.19.4, 15=1.20.1, 18=1.20.2+, 22=1.20.5+
    """
    return {
        "pack": {
            "pack_format": pack_format,
            "description": description
        }
    }


def extract_texture_from_bbmodel(bbmodel_path, output_png_path):
    """Le o bbmodel JSON, extrai a textura base64 embutida, salva como PNG."""
    with open(bbmodel_path, "r", encoding="utf-8") as f:
        bb = json.load(f)
    textures = bb.get("textures", [])
    if not textures:
        return False, "bbmodel sem texturas"
    tex = textures[0]
    source = tex.get("source", "")
    if not source.startswith("data:image/png;base64,"):
        return False, f"textura nao eh base64 PNG (source: {source[:50]}...)"
    b64 = source.replace("data:image/png;base64,", "")
    png_bytes = base64.b64decode(b64)
    with open(output_png_path, "wb") as f:
        f.write(png_bytes)
    return True, f"{len(png_bytes)} bytes extraidos"


def build_pack_from_bbmodel(bbmodel_path, output_zip, name, mod_id="liberthia",
                              pack_format=15, description=None):
    """Constroi resource pack a partir de bbmodel."""
    with open(bbmodel_path, "r", encoding="utf-8") as f:
        bb = json.load(f)

    # Convert bbmodel elements para Minecraft block model format
    block_model = {
        "credit": "Generated by bb_to_resourcepack.py",
        "textures": {
            "0": f"{mod_id}:block/{name}",
            "particle": f"{mod_id}:block/{name}"
        },
        "elements": []
    }

    for el in bb.get("elements", []):
        if el.get("type") != "cube":
            continue
        element = {
            "from": el["from"],
            "to": el["to"],
            "faces": {}
        }
        for face, fdata in el.get("faces", {}).items():
            element["faces"][face] = {
                "uv": fdata.get("uv", [0, 0, 16, 16]),
                "texture": "#0"
            }
        block_model["elements"].append(element)

    # Extract embedded texture
    tmp_png = output_zip + ".tmp.png"
    ok, msg = extract_texture_from_bbmodel(bbmodel_path, tmp_png)
    if not ok:
        return False, msg

    # Build ZIP structure
    desc = description or f"Resource pack: {name} (auto-generated)"
    pack_mcmeta = create_pack_mcmeta(desc, pack_format)

    blockstate = {"variants": {"": {"model": f"{mod_id}:block/{name}"}}}
    item_model = {"parent": f"{mod_id}:block/{name}"}

    with zipfile.ZipFile(output_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        # pack.mcmeta na raiz
        zf.writestr("pack.mcmeta", json.dumps(pack_mcmeta, indent=2))
        # Block model
        zf.writestr(f"assets/{mod_id}/models/block/{name}.json",
                    json.dumps(block_model, indent=2))
        # Item model
        zf.writestr(f"assets/{mod_id}/models/item/{name}.json",
                    json.dumps(item_model, indent=2))
        # Blockstate
        zf.writestr(f"assets/{mod_id}/blockstates/{name}.json",
                    json.dumps(blockstate, indent=2))
        # Texture
        with open(tmp_png, "rb") as f:
            zf.writestr(f"assets/{mod_id}/textures/block/{name}.png", f.read())

    os.remove(tmp_png)
    return True, "OK"


def build_pack_from_mod_assets(mod_root, name, mod_id, output_zip,
                                 pack_format=15, description=None):
    """Constroi pack a partir de assets ja no mod (model JSON + PNG existentes)."""
    assets_root = os.path.join(mod_root, "assets", mod_id)
    block_model_path = os.path.join(assets_root, "models", "block", f"{name}.json")
    item_model_path = os.path.join(assets_root, "models", "item", f"{name}.json")
    blockstate_path = os.path.join(assets_root, "blockstates", f"{name}.json")
    texture_path = os.path.join(assets_root, "textures", "block", f"{name}.png")

    for p in [block_model_path, texture_path]:
        if not os.path.exists(p):
            return False, f"nao encontrado: {p}"

    desc = description or f"Resource pack: {name}"
    pack_mcmeta = create_pack_mcmeta(desc, pack_format)

    with zipfile.ZipFile(output_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("pack.mcmeta", json.dumps(pack_mcmeta, indent=2))
        for path, archive_path in [
            (block_model_path, f"assets/{mod_id}/models/block/{name}.json"),
            (texture_path, f"assets/{mod_id}/textures/block/{name}.png")
        ]:
            with open(path, "rb") as f:
                zf.writestr(archive_path, f.read())
        if os.path.exists(item_model_path):
            with open(item_model_path, "rb") as f:
                zf.writestr(f"assets/{mod_id}/models/item/{name}.json", f.read())
        else:
            item_json = {"parent": f"{mod_id}:block/{name}"}
            zf.writestr(f"assets/{mod_id}/models/item/{name}.json",
                        json.dumps(item_json, indent=2))
        if os.path.exists(blockstate_path):
            with open(blockstate_path, "rb") as f:
                zf.writestr(f"assets/{mod_id}/blockstates/{name}.json", f.read())
        else:
            bs = {"variants": {"": {"model": f"{mod_id}:block/{name}"}}}
            zf.writestr(f"assets/{mod_id}/blockstates/{name}.json",
                        json.dumps(bs, indent=2))
    return True, "OK"


def main():
    ap = argparse.ArgumentParser(description="Empacota assets de bloco num resource pack ZIP")
    ap.add_argument("--bbmodel", help="Caminho do .bbmodel a empacotar (textura embedded)")
    ap.add_argument("--from-mod-name", help="Nome do bloco ja existente no mod")
    ap.add_argument("--mod-root", default=None, help="Root assets (default: ../src/main/resources)")
    ap.add_argument("--mod-id", default="liberthia")
    ap.add_argument("--name", default=None, help="Nome do bloco (sobrescreve detectado)")
    ap.add_argument("--output", required=True, help="Caminho do ZIP de saida")
    ap.add_argument("--pack-format", type=int, default=15,
                     help="MC pack format (15=1.20.1, 18=1.20.2+, 22=1.20.5+)")
    ap.add_argument("--description", default=None)
    args = ap.parse_args()

    if not args.bbmodel and not args.from_mod_name:
        print("ERRO: precisa de --bbmodel OU --from-mod-name")
        sys.exit(1)

    if args.bbmodel:
        if not os.path.exists(args.bbmodel):
            print(f"ERRO: {args.bbmodel} nao encontrado")
            sys.exit(1)
        name = args.name or os.path.splitext(os.path.basename(args.bbmodel))[0]
        name = name.lower().replace(" ", "_").replace("-", "_")
        print(f"[1/2] Empacotando bbmodel: {args.bbmodel}")
        ok, msg = build_pack_from_bbmodel(
            args.bbmodel, args.output, name, args.mod_id,
            args.pack_format, args.description)
    else:
        name = args.name or args.from_mod_name
        mod_root = args.mod_root or os.path.normpath(
            os.path.join(os.path.dirname(__file__), "..", "src/main/resources"))
        print(f"[1/2] Empacotando assets do mod: {name}")
        ok, msg = build_pack_from_mod_assets(
            mod_root, name, args.mod_id, args.output,
            args.pack_format, args.description)

    if not ok:
        print(f"FAIL: {msg}")
        sys.exit(1)

    sz = os.path.getsize(args.output)
    print(f"[2/2] [OK] Pack gerado: {args.output} ({sz//1024} KB)")
    print(f"")
    print(f"=== COMO USAR ===")
    print(f"OPCAO A - Como resource pack:")
    print(f"  Copia o ZIP pra: %appdata%/.minecraft/resourcepacks/")
    print(f"  No MC: Options > Resource Packs > seleciona")
    print(f"")
    print(f"OPCAO B - Como mod asset:")
    print(f"  Descompacta dentro de src/main/resources/")
    print(f"  Rebuild o mod com ./gradlew build")
    print(f"")
    print(f"OPCAO C - Mandar pra alguem:")
    print(f"  Envia o ZIP. Pessoa joga em resourcepacks/ ou descompacta no mod dela.")


if __name__ == "__main__":
    main()
