"""Converte GLTF/GLB pra usar com Forge OBJ Loader — SEM VOXELIZAR.

Resultado: mesh triangulado completo, com todo detalhe original preservado.
Funciona em items/blocos do Forge 1.16+. Renderiza qualquer geometria.

Output:
- assets/<mod>/models/item/<name>.obj      ← mesh OBJ
- assets/<mod>/models/item/<name>.mtl      ← material
- assets/<mod>/models/item/<name>.json     ← model JSON forge-loader
- assets/<mod>/textures/item/<name>.png    ← textura

Usage:
    python gltf_to_forge_obj.py modelo.glb --name minha_espada --texture textura.png
"""
import sys, os, json, argparse
import trimesh
import numpy as np
from PIL import Image


def export_obj(mesh, output_obj, output_mtl, mtl_name, texture_name):
    """Exporta trimesh como .obj + .mtl referenciando textura.

    Centraliza modelo + scale pra caber em 16x16x16 (block model space).
    """
    bounds = mesh.bounds
    center = (bounds[0] + bounds[1]) / 2
    extent = bounds[1] - bounds[0]
    max_dim = extent.max()
    if max_dim == 0:
        max_dim = 1
    # Scale pra max dim = 16 unidades
    scale = 16.0 / max_dim

    # Vertices centralizados + escalados (origem no centro do bloco)
    verts = (mesh.vertices - center) * scale + np.array([0, 0, 0])
    # Adiciona offset pro origem do bloco MC (8,8,8) — Forge OBJ usa coord 0-16 com 0,0,0 no canto
    verts = verts + np.array([0, 8, 0])  # vertical center 8 (block center)

    uvs = None
    if hasattr(mesh.visual, 'uv') and mesh.visual.uv is not None:
        uvs = mesh.visual.uv

    with open(output_obj, "w", encoding="utf-8") as f:
        f.write(f"# Generated by gltf_to_forge_obj.py\n")
        f.write(f"mtllib {os.path.basename(output_mtl)}\n")
        f.write(f"o {mtl_name}\n")

        # Vertices
        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")

        # UVs (se tiver)
        if uvs is not None:
            for uv in uvs:
                # OBJ UV: V vai de 0 (top) a 1 (bottom). Flip Y se precisar.
                f.write(f"vt {uv[0]:.4f} {uv[1]:.4f}\n")

        # Normais
        try:
            normals = mesh.face_normals
            for n in normals:
                f.write(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n")
        except Exception:
            normals = None

        f.write(f"usemtl {mtl_name}\n")
        f.write(f"s off\n")

        # Faces (OBJ usa 1-indexed)
        for fi, face in enumerate(mesh.faces):
            v_indices = [vi + 1 for vi in face]
            if uvs is not None and normals is not None:
                # Format: v/vt/vn  v/vt/vn  v/vt/vn
                fparts = [f"{vi}/{vi}/{fi+1}" for vi in v_indices]
            elif uvs is not None:
                fparts = [f"{vi}/{vi}" for vi in v_indices]
            else:
                fparts = [str(vi) for vi in v_indices]
            f.write(f"f " + " ".join(fparts) + "\n")

    # MTL file
    with open(output_mtl, "w", encoding="utf-8") as f:
        f.write(f"newmtl {mtl_name}\n")
        f.write(f"Ka 1.000 1.000 1.000\n")
        f.write(f"Kd 1.000 1.000 1.000\n")
        f.write(f"Ks 0.000 0.000 0.000\n")
        f.write(f"d 1.0\n")
        f.write(f"illum 2\n")
        f.write(f"map_Kd {texture_name}\n")


def make_forge_model_json(obj_ref, texture_ref):
    """Gera JSON model pro Forge OBJ Loader."""
    return {
        "loader": "forge:obj",
        "flip_v": True,
        "model": obj_ref,
        "textures": {
            "#default": texture_ref,
            "particle": texture_ref
        },
        "display": {
            "thirdperson_righthand": {
                "rotation": [-90, 0, 0],
                "translation": [0, 1, -3],
                "scale": [0.55, 0.55, 0.55]
            },
            "thirdperson_lefthand": {
                "rotation": [-90, 0, 0],
                "translation": [0, 1, -3],
                "scale": [0.55, 0.55, 0.55]
            },
            "firstperson_righthand": {
                "rotation": [0, -90, 25],
                "translation": [1.13, 3.2, 1.13],
                "scale": [0.68, 0.68, 0.68]
            },
            "firstperson_lefthand": {
                "rotation": [0, 90, -25],
                "translation": [1.13, 3.2, 1.13],
                "scale": [0.68, 0.68, 0.68]
            },
            "ground": {"translation": [0, 4, 0], "scale": [0.5, 0.5, 0.5]},
            "head": {"translation": [0, 13, 7], "scale": [1, 1, 1]},
            "fixed": {"rotation": [0, 0, 0], "scale": [1, 1, 1]},
            "gui": {
                "rotation": [30, 225, 0],
                "translation": [0, 0, 0],
                "scale": [0.625, 0.625, 0.625]
            }
        }
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("--name", required=True)
    ap.add_argument("--texture", default=None,
                     help="Caminho da textura PNG (se nao informar, tenta pegar embedded)")
    ap.add_argument("--mod-id", default="liberthia")
    ap.add_argument("--mod-root", default=None)
    ap.add_argument("--type", choices=["item", "block"], default="item")
    args = ap.parse_args()

    print(f"[1/4] Loading: {args.input}")
    mesh = trimesh.load(args.input, force='mesh')
    if isinstance(mesh, trimesh.Scene):
        print(f"      Scene -> concatenating {len(mesh.geometry)} geometries")
        mesh = trimesh.util.concatenate(tuple(mesh.dump()))
    print(f"      tris: {len(mesh.faces)}, vertices: {len(mesh.vertices)}")
    print(f"      bounds: {mesh.bounds[0]} -> {mesh.bounds[1]}")

    # Try to extract embedded texture
    extracted_tex = None
    if args.texture is None:
        try:
            if hasattr(mesh.visual, 'material') and mesh.visual.material:
                mat = mesh.visual.material
                if hasattr(mat, 'image') and mat.image:
                    extracted_tex = mat.image
        except Exception:
            pass

    mod_root = args.mod_root or os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "src/main/resources"))
    assets = os.path.join(mod_root, "assets", args.mod_id)

    # Paths
    if args.type == "item":
        model_dir = os.path.join(assets, "models", "item")
        tex_dir = os.path.join(assets, "textures", "item")
        tex_ref_prefix = "item"
    else:
        model_dir = os.path.join(assets, "models", "block")
        tex_dir = os.path.join(assets, "textures", "block")
        tex_ref_prefix = "block"
    os.makedirs(model_dir, exist_ok=True)
    os.makedirs(tex_dir, exist_ok=True)

    obj_path = os.path.join(model_dir, f"{args.name}.obj")
    mtl_path = os.path.join(model_dir, f"{args.name}.mtl")
    json_path = os.path.join(model_dir, f"{args.name}.json")
    tex_path = os.path.join(tex_dir, f"{args.name}.png")

    print(f"[2/4] Writing texture: {os.path.relpath(tex_path, mod_root)}")
    if args.texture and os.path.exists(args.texture):
        Image.open(args.texture).convert("RGBA").save(tex_path)
    elif extracted_tex is not None:
        extracted_tex.save(tex_path)
    else:
        # Cria placeholder
        Image.new("RGBA", (16, 16), (180, 180, 180, 255)).save(tex_path)

    print(f"[3/4] Writing OBJ + MTL")
    print(f"      OBJ: {os.path.relpath(obj_path, mod_root)}")
    print(f"      MTL: {os.path.relpath(mtl_path, mod_root)}")
    export_obj(mesh, obj_path, mtl_path, args.name, f"{args.name}.png")

    print(f"[4/4] Writing Forge model JSON")
    print(f"      JSON: {os.path.relpath(json_path, mod_root)}")
    model_json = make_forge_model_json(
        f"{args.mod_id}:models/{tex_ref_prefix}/{args.name}.obj",
        f"{args.mod_id}:{tex_ref_prefix}/{args.name}"
    )
    with open(json_path, "w") as f:
        json.dump(model_json, f, indent=2)

    # Se for bloco, cria blockstate tb
    if args.type == "block":
        bs_dir = os.path.join(assets, "blockstates")
        os.makedirs(bs_dir, exist_ok=True)
        with open(os.path.join(bs_dir, f"{args.name}.json"), "w") as f:
            json.dump({"variants": {"": {"model": f"{args.mod_id}:block/{args.name}"}}}, f)
        # Item de bloco
        item_dir = os.path.join(assets, "models", "item")
        os.makedirs(item_dir, exist_ok=True)
        with open(os.path.join(item_dir, f"{args.name}.json"), "w") as f:
            json.dump({"parent": f"{args.mod_id}:block/{args.name}"}, f)

    print(f"")
    print(f"=== DONE === Mesh com DETALHE COMPLETO preservado!")
    print(f"")
    print(f"PROXIMOS PASSOS:")
    print(f"1. No build.gradle do mod, adiciona dependencia (geralmente ja tem):")
    print(f"   minecraft 'net.minecraftforge:forge:1.20.1-47.x'")
    print(f"")
    print(f"2. No Java, registra item/bloco normalmente. Loader 'forge:obj' eh built-in.")
    print(f"")
    print(f"3. Pode usar com ANY mesh complexa — sem voxelizacao!")


if __name__ == "__main__":
    main()
