/**
 * Listas estáticas do vanilla MC 1.20.1 — usadas como autocomplete em UI.
 * Não dependem do mod (são hardcoded). Items + enchantments puxados via API
 * porque incluem mods custom (Liberthia tem ~277 items).
 */

export const VANILLA_EFFECTS = [
  'minecraft:speed', 'minecraft:slowness', 'minecraft:haste', 'minecraft:mining_fatigue',
  'minecraft:strength', 'minecraft:instant_health', 'minecraft:instant_damage',
  'minecraft:jump_boost', 'minecraft:nausea', 'minecraft:regeneration',
  'minecraft:resistance', 'minecraft:fire_resistance', 'minecraft:water_breathing',
  'minecraft:invisibility', 'minecraft:blindness', 'minecraft:night_vision',
  'minecraft:hunger', 'minecraft:weakness', 'minecraft:poison', 'minecraft:wither',
  'minecraft:health_boost', 'minecraft:absorption', 'minecraft:saturation',
  'minecraft:glowing', 'minecraft:levitation', 'minecraft:luck', 'minecraft:unluck',
  'minecraft:slow_falling', 'minecraft:conduit_power', 'minecraft:dolphins_grace',
  'minecraft:bad_omen', 'minecraft:hero_of_the_village', 'minecraft:darkness',
] as const

export const VANILLA_PARTICLES = [
  'minecraft:angry_villager', 'minecraft:ash', 'minecraft:block', 'minecraft:bubble',
  'minecraft:bubble_column_up', 'minecraft:bubble_pop', 'minecraft:campfire_cosy_smoke',
  'minecraft:campfire_signal_smoke', 'minecraft:cherry_leaves', 'minecraft:cloud',
  'minecraft:composter', 'minecraft:crimson_spore', 'minecraft:crit',
  'minecraft:current_down', 'minecraft:damage_indicator', 'minecraft:dolphin',
  'minecraft:dragon_breath', 'minecraft:dripping_dripstone_lava',
  'minecraft:dripping_dripstone_water', 'minecraft:dripping_honey',
  'minecraft:dripping_lava', 'minecraft:dripping_obsidian_tear', 'minecraft:dripping_water',
  'minecraft:dust', 'minecraft:dust_color_transition', 'minecraft:dust_plume',
  'minecraft:effect', 'minecraft:egg_crack', 'minecraft:elder_guardian',
  'minecraft:electric_spark', 'minecraft:enchant', 'minecraft:enchanted_hit',
  'minecraft:end_rod', 'minecraft:entity_effect', 'minecraft:explosion',
  'minecraft:explosion_emitter', 'minecraft:falling_dripstone_lava',
  'minecraft:falling_dripstone_water', 'minecraft:falling_dust',
  'minecraft:falling_honey', 'minecraft:falling_lava', 'minecraft:falling_nectar',
  'minecraft:falling_obsidian_tear', 'minecraft:falling_spore_blossom',
  'minecraft:falling_water', 'minecraft:firework', 'minecraft:fishing',
  'minecraft:flame', 'minecraft:flash', 'minecraft:glow', 'minecraft:glow_squid_ink',
  'minecraft:happy_villager', 'minecraft:heart', 'minecraft:instant_effect',
  'minecraft:item', 'minecraft:item_slime', 'minecraft:item_snowball',
  'minecraft:landing_honey', 'minecraft:landing_lava', 'minecraft:landing_obsidian_tear',
  'minecraft:large_smoke', 'minecraft:lava', 'minecraft:mycelium',
  'minecraft:nautilus', 'minecraft:note', 'minecraft:poof', 'minecraft:portal',
  'minecraft:rain', 'minecraft:reverse_portal', 'minecraft:scrape',
  'minecraft:sculk_charge', 'minecraft:sculk_charge_pop', 'minecraft:sculk_soul',
  'minecraft:shriek', 'minecraft:small_flame', 'minecraft:smoke', 'minecraft:sneeze',
  'minecraft:snowflake', 'minecraft:sonic_boom', 'minecraft:soul', 'minecraft:soul_fire_flame',
  'minecraft:spit', 'minecraft:splash', 'minecraft:spore_blossom_air',
  'minecraft:squid_ink', 'minecraft:sweep_attack', 'minecraft:totem_of_undying',
  'minecraft:trial_spawner_detection', 'minecraft:underwater', 'minecraft:vibration',
  'minecraft:warped_spore', 'minecraft:wax_off', 'minecraft:wax_on',
  'minecraft:white_ash', 'minecraft:white_smoke', 'minecraft:witch',
] as const

export const VANILLA_ENTITIES = [
  // Passivos
  'minecraft:allay', 'minecraft:armor_stand', 'minecraft:axolotl', 'minecraft:bat',
  'minecraft:bee', 'minecraft:camel', 'minecraft:cat', 'minecraft:chicken',
  'minecraft:cod', 'minecraft:cow', 'minecraft:dolphin', 'minecraft:donkey',
  'minecraft:fox', 'minecraft:frog', 'minecraft:glow_squid', 'minecraft:goat',
  'minecraft:horse', 'minecraft:llama', 'minecraft:mooshroom', 'minecraft:mule',
  'minecraft:ocelot', 'minecraft:panda', 'minecraft:parrot', 'minecraft:pig',
  'minecraft:polar_bear', 'minecraft:pufferfish', 'minecraft:rabbit',
  'minecraft:salmon', 'minecraft:sheep', 'minecraft:skeleton_horse', 'minecraft:sniffer',
  'minecraft:snow_golem', 'minecraft:squid', 'minecraft:strider', 'minecraft:tadpole',
  'minecraft:tropical_fish', 'minecraft:turtle', 'minecraft:villager',
  'minecraft:wandering_trader', 'minecraft:wolf',
  // Hostis
  'minecraft:blaze', 'minecraft:breeze', 'minecraft:cave_spider', 'minecraft:creeper',
  'minecraft:drowned', 'minecraft:elder_guardian', 'minecraft:ender_dragon',
  'minecraft:enderman', 'minecraft:endermite', 'minecraft:evoker', 'minecraft:ghast',
  'minecraft:giant', 'minecraft:guardian', 'minecraft:hoglin', 'minecraft:husk',
  'minecraft:illusioner', 'minecraft:iron_golem', 'minecraft:magma_cube',
  'minecraft:phantom', 'minecraft:piglin', 'minecraft:piglin_brute', 'minecraft:pillager',
  'minecraft:ravager', 'minecraft:shulker', 'minecraft:silverfish', 'minecraft:skeleton',
  'minecraft:slime', 'minecraft:spider', 'minecraft:stray', 'minecraft:vex',
  'minecraft:vindicator', 'minecraft:warden', 'minecraft:witch', 'minecraft:wither',
  'minecraft:wither_skeleton', 'minecraft:zoglin', 'minecraft:zombie',
  'minecraft:zombie_villager', 'minecraft:zombified_piglin',
  // Outros
  'minecraft:lightning_bolt', 'minecraft:falling_block', 'minecraft:item',
  'minecraft:experience_orb', 'minecraft:tnt', 'minecraft:fireball',
  'minecraft:small_fireball', 'minecraft:dragon_fireball', 'minecraft:wither_skull',
  'minecraft:arrow', 'minecraft:spectral_arrow', 'minecraft:trident',
  'minecraft:fishing_bobber', 'minecraft:firework_rocket', 'minecraft:area_effect_cloud',
  'minecraft:end_crystal', 'minecraft:eye_of_ender', 'minecraft:potion',
  'minecraft:experience_bottle', 'minecraft:snowball', 'minecraft:egg',
  'minecraft:ender_pearl', 'minecraft:llama_spit',
] as const

export const COMMON_SOUNDS = [
  // Ambient / horror
  'minecraft:ambient.cave', 'minecraft:ambient.warped_forest.loop',
  'minecraft:ambient.crimson_forest.loop', 'minecraft:ambient.basalt_deltas.loop',
  'minecraft:ambient.soul_sand_valley.loop', 'minecraft:ambient.nether_wastes.loop',
  // Entidades
  'minecraft:entity.warden.heartbeat', 'minecraft:entity.warden.angry',
  'minecraft:entity.warden.sonic_boom', 'minecraft:entity.warden.roar',
  'minecraft:entity.ghast.scream', 'minecraft:entity.ghast.warn',
  'minecraft:entity.wither.spawn', 'minecraft:entity.wither.death',
  'minecraft:entity.ender_dragon.growl', 'minecraft:entity.ender_dragon.death',
  'minecraft:entity.zombie.ambient', 'minecraft:entity.skeleton.ambient',
  'minecraft:entity.creeper.primed', 'minecraft:entity.creeper.death',
  'minecraft:entity.evoker.prepare_summon', 'minecraft:entity.evoker.cast_spell',
  'minecraft:entity.allay.ambient_with_item', 'minecraft:entity.allay.ambient_without_item',
  'minecraft:entity.lightning_bolt.thunder', 'minecraft:entity.lightning_bolt.impact',
  'minecraft:entity.item.pickup', 'minecraft:entity.player.levelup',
  // Blocos
  'minecraft:block.bell.use', 'minecraft:block.bell.resonate',
  'minecraft:block.note_block.bit', 'minecraft:block.note_block.bell',
  'minecraft:block.note_block.chime', 'minecraft:block.note_block.harp',
  'minecraft:block.note_block.pling', 'minecraft:block.note_block.flute',
  'minecraft:block.note_block.banjo', 'minecraft:block.note_block.cow_bell',
  'minecraft:block.note_block.didgeridoo', 'minecraft:block.note_block.guitar',
  'minecraft:block.note_block.hat', 'minecraft:block.note_block.snare',
  'minecraft:block.note_block.basedrum', 'minecraft:block.note_block.bass',
  'minecraft:block.amethyst_block.chime', 'minecraft:block.amethyst_block.resonate',
  'minecraft:block.amethyst_block.break', 'minecraft:block.amethyst_cluster.break',
  'minecraft:block.beacon.ambient', 'minecraft:block.beacon.activate',
  'minecraft:block.beacon.deactivate', 'minecraft:block.beacon.power_select',
  'minecraft:block.portal.ambient', 'minecraft:block.portal.travel',
  'minecraft:block.portal.trigger',
  'minecraft:block.sculk.charge', 'minecraft:block.sculk.spread',
  'minecraft:block.sculk.hit', 'minecraft:block.sculk.break', 'minecraft:block.sculk.place',
  'minecraft:block.sculk_shrieker.shriek',
  'minecraft:block.respawn_anchor.set_spawn', 'minecraft:block.respawn_anchor.deplete',
  'minecraft:block.respawn_anchor.charge',
  'minecraft:block.fire.ambient', 'minecraft:block.fire.extinguish',
  'minecraft:block.water.ambient', 'minecraft:block.lava.ambient',
  'minecraft:block.glass.break',
  // UI / effects
  'minecraft:ui.button.click', 'minecraft:ui.toast.in', 'minecraft:ui.toast.out',
  'minecraft:item.totem.use', 'minecraft:item.armor.equip_diamond',
  'minecraft:music_disc.13', 'minecraft:music_disc.cat', 'minecraft:music_disc.pigstep',
] as const

export const VANILLA_ENCHANTMENTS = [
  'minecraft:protection', 'minecraft:fire_protection', 'minecraft:feather_falling',
  'minecraft:blast_protection', 'minecraft:projectile_protection', 'minecraft:respiration',
  'minecraft:aqua_affinity', 'minecraft:thorns', 'minecraft:depth_strider',
  'minecraft:frost_walker', 'minecraft:binding_curse', 'minecraft:soul_speed',
  'minecraft:swift_sneak', 'minecraft:sharpness', 'minecraft:smite',
  'minecraft:bane_of_arthropods', 'minecraft:knockback', 'minecraft:fire_aspect',
  'minecraft:looting', 'minecraft:sweeping', 'minecraft:efficiency',
  'minecraft:silk_touch', 'minecraft:unbreaking', 'minecraft:fortune',
  'minecraft:power', 'minecraft:punch', 'minecraft:flame', 'minecraft:infinity',
  'minecraft:luck_of_the_sea', 'minecraft:lure', 'minecraft:loyalty',
  'minecraft:impaling', 'minecraft:riptide', 'minecraft:channeling',
  'minecraft:multishot', 'minecraft:quick_charge', 'minecraft:piercing',
  'minecraft:mending', 'minecraft:vanishing_curse',
] as const

/** Pequena lista de comandos vanilla úteis pra preview/autocomplete em campos free-form. */
export const COMMON_COMMANDS = [
  'tellraw {target} {"text":""}',
  'title {target} title {"text":""}',
  'title {target} subtitle {"text":""}',
  'title {target} actionbar {"text":""}',
  'effect give {target} minecraft:speed 60 1',
  'effect clear {target}',
  'give {target} minecraft:diamond 1',
  'clear {target}',
  'tp {target} 0 80 0',
  'summon minecraft:zombie ~ ~ ~',
  'playsound minecraft:block.bell.use master {target}',
  'particle minecraft:end_rod ~ ~ ~ 0 0 0 0.1 30',
  'gamemode survival {target}',
  'gamemode creative {target}',
  'kill {target}',
  'weather clear',
  'weather thunder',
  'time set day',
  'time set night',
  'fill ~-1 ~-1 ~-1 ~1 ~1 ~1 minecraft:stone',
  'setblock ~ ~ ~ minecraft:bedrock',
  'difficulty hard',
  'gamerule keepInventory true',
  'execute as @a at @s run particle minecraft:end_rod ~ ~ ~ 0 0 0 0.1 5',
] as const

/** Dimensões mais comuns. */
export const DIMENSIONS = [
  { id: 'overworld', label: 'Overworld 🌍' },
  { id: 'the_nether', label: 'Nether 🔥' },
  { id: 'the_end', label: 'End 🌌' },
] as const
